# ========================
# Application
# ========================
spring.application.name=url-shortener
server.port=${PORT:8080}

# ========================
# Database
# ========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
app.base-url=${BASE_URL}
app.short-code-length=6

# HikariCP
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000

# ========================
# JPA
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ========================
# Cache
# ========================
spring.cache.type=simple

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# ========================
# App
# ========================
app.base-url=${BASE_URL}
app.short-code-length=6
